### PR TITLE
Settings.js

### PR DESCRIPTION
**Pull request by CrypticPoet**
Fixed a minor bug that enabled entering empty fields

### CODE REVIEW

**Comment by CrypticPoet** [comment]
Also, merge my pull request only after Merging the social auth one, the conflicts will get resolved themselves

**Comment by Harsh14901** [comment]
I think fields like first name and last name should not be mandatory, and what if someone wants to remove their last name and just keep the first name? I think this filter should be applied only to the username and not on first or last name.

**Comment by bicycleman15** [comment]
yeah @Harsh14901, makes sense. can you do the changes @CrypticPoet

**Comment by CrypticPoet** [comment]
@Harsh14901 none of the fields in the settings page are mandatory. First name and last name are displayed for everyone because I think it's mandatory on the register page. I can add an option to remove Firstname and lastname entirely though. Are you sure it won't cause any problems with the JWT though if the lastname is an empty string for example?

**Comment by Harsh14901** [comment]
No it won't be a problem

**Comment by bicycleman15** [comment]
There are still conflicts, @CrypticPoet  resolve them and then I will merge :clinking_glasses:

**Comment by bicycleman15** [comment]
Should I merge now or there are more changes to be made ?

**Pull request merged**
